[package]
name = "munira"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20.0", features = ["full"] }
rusqlite = { version = "0.28.0", features = ["bundled", "array", "vtab"] }
chrono = "0.4.19"
futures = "0.3.21"
anyhow = "1.0.58"
